/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example;

public class App {
    public String getGreeting() {
        return "Function Pointer Example.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Runnable r1 = () -> System.out.println("Example 1: Running in a thread");
        Runnable r2 = () -> {
            System.out.println("Example 2");
            for(int i=0; i<10; i++) {
                System.out.println("i: " + i);
            }
        };

        Thread t1 = new Thread(r1);
        t1.start();
        Thread t2 = new Thread(r2);
        t2.start();

        new Thread( () -> System.out.println("Another example.") ).start();
    }
}
