/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exemplo.media;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void instanceTest() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest);
    }

    @Test void mediaExampleTest() {
        double notas[] = {6.0, 7.0};
        double media = App.media(notas);
        assertEquals(6.5, media, 0.01);
    }
}
